// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weylieuzfkbnwhymxqdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndleWxpZXV6ZmtibndoeW14cWRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzUxMjIsImV4cCI6MjA2NTQ1MTEyMn0.YL7qdqIOnUXk4mhS8WsN1Di0zTiuxikUF0i2bHnaBHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);